The general algorithm
kimt33/Flik pull request #14
Opened 2018-03-02 04:28 UTC by crisely09

There is probably a better way to select the conditions...

2018-03-02 14:40 UTC, kimt33 requested changes

2018-03-02 14:40 UTC, kimt33 commented on flik/linesearch/linesearch.py
> +    conditions: str or list of str
{str, list of str}

2018-03-02 14:40 UTC, kimt33 commented on flik/linesearch/linesearch.py
> +    const1: float
{float, 1e-4}

2018-03-02 14:40 UTC, kimt33 commented on flik/linesearch/linesearch.py
> +    const2: float
{float, 1e-2}

2018-03-02 14:40 UTC, kimt33 commented on flik/linesearch/linesearch.py
> +    if len(conditions) > 1:
if len(conditions) == len(set(conditions))

2018-03-02 14:40 UTC, kimt33 commented on flik/linesearch/linesearch.py
> +            raise ValueError("Condition %d+1 is not implemented." % i)
raise ValueError('Condition, {}, is not supported'.format(condition))
remove enumerate

2018-03-02 14:40 UTC, kimt33 commented on flik/linesearch/linesearch.py
> +                    return alpha_new
The algorithm doesn't quite do what it says it'll do. It doesn't make sure that all of the conditions are satisfied. It just returns the first alpha that satisfies one of the conditions.

2018-03-02 15:01 UTC, kimt33 commented
I've made the requested changes. It doesn't seem to converge though.

2018-03-02 15:39 UTC, crisely09 commented on flik/linesearch/linesearch.py
> +            if satisfies_conditions(alpha_new):
This is definitely a nicer way to do it.

2018-03-30 23:31 UTC, merged

2018-03-30 23:31 UTC, kimt33 commented
I'm merging this, even though the line search module is not complete. This way, we can have all the code available to us when we refactor the line search module.