Quadratic Approximation
kimt33/Flik pull request #3
Opened 2018-02-26 07:45 UTC by kumrud

2018-02-27 20:56 UTC, crisely09 commented
Hey, I was writing the zoom function and it seems to me that all interpolation functions should take general values of alpha, i.e., instead of having phi_zero and phi_alpha, we have phi_alphai and phi_alphaj, for example. Then phi_zero = phi_alphai when alphai = 0.

2018-02-28 19:50 UTC, kimt33 requested changes

2018-02-28 19:50 UTC, kimt33 commented on flik/linesearch/interpolations.py
> +    if not 0 < alpha < 1:
I think alpha can be 1.

2018-02-28 19:50 UTC, kimt33 commented on flik/linesearch/interpolations.py
> +    if not isinstance(func(val), float):
It would be better to move the `phi_zero`'s and use `phi_zero` and `phi_zero_prime` instead.

2018-02-28 19:50 UTC, kimt33 commented on flik/linesearch/interpolations.py
> +    if not isinstance(grad(val), np.ndarray):
```python
    if not (isinstance(phi_zero_prime, np.ndarray) and phi_zero_prime.ndim == 1):
```

2018-02-28 19:50 UTC, kimt33 commented on flik/linesearch/test/test_interpolations.py
> +    assert_raises(TypeError, quad_approx, func_w, grad, val, alpha, direction)
you can probably use a lambda function here:
```python
   assert_raises(TypeError, quad_approx, lambda val: val**2, grad, val, alpha, direction)
```

2018-02-28 19:50 UTC, kimt33 commented on flik/linesearch/test/test_interpolations.py
> +    assert_raises(TypeError, quad_approx, func, grad_w, val, alpha, direction)
lambda function here too

2018-03-30 22:47 UTC, kimt33 commented
I'm merging this, even though the line search module is not complete. This way, we can have all the code available to us when we refactor all the code.

2018-03-30 22:48 UTC, kimt33 approved these changes

2018-03-30 23:22 UTC, kimt33 commented
I force pushed onto quadratic fixing the merge conflicts

2018-03-30 23:29 UTC, merged